name: Process Locations

on: 
    push:
        paths:
            - data/**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 #check out the repository
      - uses: r-lib/actions/setup-r@v2 #set up the R environment
      - name: Install regular packages
        run:
          Rscript -e "install.packages(c('tidygeocoder', 'sf', 'geojsonsf'), type='win.binary')"
      - name: Create Map Data
        run:
          Rscript -e "source('r/create_map_data.R')"
      - name: Commit results #Job 3: commit the changes back to the repository
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m 'Updated the locations data' || echo "Updated the locations data"
          git push origin || echo "Updated the locations data"